sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-secret: 
    access-key-id: 
    bucket-name: sky-cip
  redis:
    port: 6379
    password: 123456
    host: localhost
    database: 1
  wechat:
    appid: wx7a7925c7b88a31ec
    secret: 1713de2dc0797a568ec68ffc5aad4664
          #TODO 上线后补全
    mchid:                          #商户号
    mchSerialNo:                    #对应证书序列号
    privateKeyFilePath:             #私钥文件地址
    apiV3Key:                       #解密密钥
    weChatPayCertFilePath:          #平台证书文件
    notifyUrl:                      #支付成功回调地址
    refundNotifyUrl:                #退款回调地址


